### ISSUE TITLE
cv-button.vue:1 Uncaught TypeError: Cannot read properties of undefined (reading '_c')     at Proxy.a (cv-button.vue:1:58)

### ISSUE THREAD

**Issue by zogich** [carbon-design-system/carbon-components-vue#1490]
## cv-button.vue:1 Uncaught TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.a (cv-button.vue:1:58)

> Hello, i have fresh Vue 3 project created with  npm init vue@latest

> I followed instructions from https://carbondesignsystem.com/developing/vue-tutorial/overview/

> But when i but when i try to use the component i get the error: 

> Uncaught TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.a (cv-button.vue:1:58)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5701:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
    at setupRenderEffect (runtime-core.esm-bundler.js:5822:5)
    at mountComponent (runtime-core.esm-bundler.js:5612:5)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at mountChildren (runtime-core.esm-bundler.js:5284:7)

> I found same issue with carbon: https://github.com/carbon-design-system/carbon-components-vue/issues/1283 
> The discussion says that the problem is due to the fact that the carbon components for vue 3 are not yet complete. Has there been any solution to this problem?

**Comment by davidnixon** [comment]
The buttons in Vue 3 do work in the [storybook](https://vue.carbondesignsystem.com/vue3/?path=/story/component-cvbuttons-cvbutton--primary). Did you install the Vue 3 carbon components?
```sh
yarn add @carbon/vue@next
```
Adding @carbon/vue without the "next" tag will install the Vue 2 components.

**Comment by zogich** [comment]
> 

Thank you very much. Adding next helped me.

**Comment by zogich** [comment]
Thank you very much. Adding 'next' helped me.
